/// <reference types="Cypress" />
export default {
  mobileToolbarBtn: ".button--grey",
  profileMenuBtn: "button.mat-focus-indicator.mat-icon-button.mat-button-base", // use eq 14
  profileSettingBtn: "app-menu-item", // use eq 13
  addNewPaymentBtn: ".button--lime-green",
  saveBtn: ".button--lime-green",
  cardNumInput: 'input[formcontrolname="creditCardNumber"]',
  cvvInput: 'input[formcontrolname="cardCode"]',
  dateInput: 'input[formcontrolname="expirationNotice"]',
  emailInput: 'input[formcontrolname="emailAddress"]',
  addressInput: 'input[formcontrolname="address1"]',
  zipInput: 'input[formcontrolname="zip"]',
  cityInput: 'input[formcontrolname="city"]',
  stateInput: 'input[formcontrolname="state"]',
  noBorderBtn: ".button--no-border",
  confirmDelete: ".button--blue.mat-raised-button",
  reasonInput: "mat-select",
  selectReason: ".mat-option-text",
  cancelBtn: ".button-primary-inverted",
  changePlanBtn: 'button[color="primary"]',
  extendBtn: ".extend-plan.ng-star-inserted",
  checkbox: 'input[type="checkbox"]',
  cardsTable: ".billing-cards",
  paymentTabs: 'div[role="tab"]',
  accountName: 'input[formcontrolname="nameOnAccount"]',
  bankName: 'input[formcontrolname="bankName"]',
  routingNumber: 'input[formcontrolname="routingNumber"]',
  accountNumber: 'input[formcontrolname="accountNumber"]',
};
