/// <reference types="Cypress" />
export default {
  customNumberBtn: ":nth-child(10) > .mat-focus-indicator",
  addPhoneNumber: ".btn-success",
  createTollFree: ".mat-card-actions > .btn",
  createVanityNumber: "#mat-tab-label-0-1",
  selectNumberTab: "#mat-tab-label-0-0",
  selectCode: 'mat-select[formcontrolname="areaCode"]',
  vanityNumberInput: 'input[formcontrolname="tollFreeSearchText"]',
  searchBtn: ".search-button",
  selectOption: 'mat-option[role="option"]',
  viewMoreBtn: '#mat-tab-content-0-0 > .mat-tab-body-content > .mat-card-actions > .btn',
  selectPreferredNumber: ".phone-list-wrapper > :nth-child(1)",
  selectInput: 'mat-select[role="combobox"]',
  purchaseBtn: ".btn-primary",
  closeBtn: ".step-header > div > .mat-focus-indicator > .mat-button-wrapper",
  creditCardInput: 'input[formcontrolname="creditCardNumber"]',
  dateInput: 'input[formcontrolname="expirationNotice"]',
  cvvInput: 'input[formcontrolname="cardCode"]',
  emailInput: 'input[formcontrolname="emailAddress"]',
  addressInput: 'input[formcontrolname="address1"]',
  zipInput: 'input[formcontrolname="zip"]',
  cityInput: 'input[formcontrolname="city"]',
  stateInput: 'input[formcontrolname="state"]',
  snackBar: ".toast > .typography-16",
};
