/// <reference types="Cypress" />
export default {
  mobileToolbarBtn: ".button--grey",
  MessageLibraryBtn:
    "button.mat-focus-indicator.mat-icon-button.mat-button-base", // use eq accordingly
  createNewMsgBtn: 'div.ng-star-inserted > .mat-focus-indicator',
  messageName: 'input[formcontrolname="messageName"]',
  selectGroupInput: "mat-form-field.mat-form-field", // use eq accordingly
  selectGroup: ".mat-option-text", // use eq accordingly
  selectVoiceMsgBtn: '#mat-checkbox-1 > .mat-checkbox-layout > .mat-checkbox-inner-container',
  selectEmailMsgBtn: '#mat-checkbox-3 > .mat-checkbox-layout > .mat-checkbox-inner-container',
  selectTextMsgBtn: '#mat-checkbox-2 > .mat-checkbox-layout > .mat-checkbox-inner-container',
  nextButton: '.--next',
  addCallerIdBtn: '.btn-create-caller-ids',
  createVoiceMsgBtn: 'button[color="primary"]',
  textarea: '[id="mat-input-2"]',
  checkbox: 'input[type="checkbox"]',
  sendMessageBtn: ".--next",
  emailSubjectInput: '[id="mat-input-1"]',
  messageTable: "app-message-list-mobile.ng-star-inserted",
  saveEditMsg: "button.button--lime-green",
  confirmDel: "button.button--blue",
  discardMessage: ".button-primary-inverted",
  textPolling: ".mat-slide-toggle.slide-toggle",
  replyToInput: 'input[formcontrolname="replyTo"]',
  emailTemplate: ".template-predefines__predifine",
  viewMsgBtn: ".button--no-border",
  phoneInput: 'input[formcontrolname="phoneNumber"]',
  scheduleToggle: '#mat-radio-5 > .mat-radio-label',
  scheduleTime: '.button--blue-border',
  termsCheckbox: 'mat-checkbox',
  scheduleMessage: '.button--lime-green',
  searchIcon: "button.mat-mini-fab",
  searchInput: "input.mat-input-element",
  sortSelect: 'mat-select',
  selectOption: 'mat-option[role="option"]',
  filterCheckbox: 'input[type="checkbox"]',
  deleteBtn: 'button[color="warn"]',
  overlayBtn: '.more-actions-overlay__action',
  previewIcon: 'mat-icon[color="primary"]',
  replicateMessage: '.replicate',
  snackBar: ".toast > .typography-16",
};
